<?php

########################################################################
# Extension Manager/Repository config file for ext: "drk_jobboard"
#
# Auto generated by Extension Builder 2013-06-28
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PHPOffice Plugin',
	'description' => 'Contains the famous PHPOffice Framework, PHPExcel, PHPWord, ...',
	'category' => 'plugin',
	'author' => 'Kay Strobach',
	'author_email' => 'typo3@kay-strobach.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>